pyuic5 loginform.ui -o loginform.py     
pyuic5 menusform.ui -o menusform.py     
pyuic5 employeeinsertform.ui -o employeeinsertform.py     
pyuic5 employeeqryform.ui -o employeeqryform.py     
pyuic5 employeeupdateform.ui -o employeeupdateform.py     
pyuic5 productinsertform.ui -o productinsertform.py     
pyuic5 productqryform.ui -o productqryform.py     
pyuic5 productupdateform.ui -o productupdateform.py
pyuic5 stockininsertform.ui -o stockininsertform.py
pyuic5 stockinqryform.ui -o stockinqryform.py