# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employeeqryform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.showlist_2 = QtWidgets.QTextEdit(Form)
        self.showlist_2.setGeometry(QtCore.QRect(10, 20, 371, 271))
        self.showlist_2.setObjectName("showlist_2")
        self.close_2 = QtWidgets.QPushButton(Form)
        self.close_2.setGeometry(QtCore.QRect(360, 270, 16, 21))
        self.close_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pic/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_2.setIcon(icon)
        self.close_2.setObjectName("close_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
