# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memberform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 338)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.idlabel = QtWidgets.QLabel(Form)
        self.idlabel.setGeometry(QtCore.QRect(100, 60, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.idlabel.setFont(font)
        self.idlabel.setObjectName("idlabel")
        self.namelabel = QtWidgets.QLabel(Form)
        self.namelabel.setGeometry(QtCore.QRect(100, 120, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.namelabel.setFont(font)
        self.namelabel.setObjectName("namelabel")
        self.emaillabel = QtWidgets.QLabel(Form)
        self.emaillabel.setGeometry(QtCore.QRect(100, 180, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.emaillabel.setFont(font)
        self.emaillabel.setObjectName("emaillabel")
        self.idtext = QtWidgets.QTextEdit(Form)
        self.idtext.setGeometry(QtCore.QRect(200, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.idtext.setFont(font)
        self.idtext.setObjectName("idtext")
        self.nametext = QtWidgets.QTextEdit(Form)
        self.nametext.setGeometry(QtCore.QRect(200, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nametext.setFont(font)
        self.nametext.setObjectName("nametext")
        self.savebutton = QtWidgets.QPushButton(Form)
        self.savebutton.setGeometry(QtCore.QRect(90, 260, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.savebutton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savebutton.setIcon(icon)
        self.savebutton.setIconSize(QtCore.QSize(15, 15))
        self.savebutton.setCheckable(False)
        self.savebutton.setObjectName("savebutton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 260, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.emailtext = QtWidgets.QLineEdit(Form)
        self.emailtext.setGeometry(QtCore.QRect(200, 180, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emailtext.setFont(font)
        self.emailtext.setText("")
        self.emailtext.setObjectName("emailtext")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.idlabel.setText(_translate("Form", "ID"))
        self.namelabel.setText(_translate("Form", "Name"))
        self.emaillabel.setText(_translate("Form", "E-mail"))
        self.idtext.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.nametext.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.savebutton.setText(_translate("Form", "save"))
        self.pushButton_2.setText(_translate("Form", "reset"))
